version: '3.8'

services:
  backend:
    build:
      context: ./weather-warning-backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./weather-warning-backend:/app

  frontend:
    build:
      context: ./weather-warning-frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'